[project]
name = "investment-ai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.0.2",
    "ollama>=0.6.1",
    "openai>=2.9.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
